// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollection(arg1, arg2) {
  return window['go']['main']['App']['AddCollection'](arg1, arg2);
}

export function AddCollectionWithParent(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCollectionWithParent'](arg1, arg2, arg3);
}

export function AddEnv(arg1) {
  return window['go']['main']['App']['AddEnv'](arg1);
}

export function AddVar(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddVar'](arg1, arg2, arg3);
}

export function ChoseFile() {
  return window['go']['main']['App']['ChoseFile']();
}

export function ClearAllCookies() {
  return window['go']['main']['App']['ClearAllCookies']();
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteCookies(arg1) {
  return window['go']['main']['App']['DeleteCookies'](arg1);
}

export function DeleteEnv(arg1) {
  return window['go']['main']['App']['DeleteEnv'](arg1);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequest'](arg1, arg2);
}

export function DeleteVar(arg1, arg2) {
  return window['go']['main']['App']['DeleteVar'](arg1, arg2);
}

export function DuplicateEnv(arg1) {
  return window['go']['main']['App']['DuplicateEnv'](arg1);
}

export function DuplicateRequest(arg1, arg2) {
  return window['go']['main']['App']['DuplicateRequest'](arg1, arg2);
}

export function ExportCollection(arg1) {
  return window['go']['main']['App']['ExportCollection'](arg1);
}

export function GetAllCookies() {
  return window['go']['main']['App']['GetAllCookies']();
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetEnvs() {
  return window['go']['main']['App']['GetEnvs']();
}

export function GetRequest(arg1, arg2) {
  return window['go']['main']['App']['GetRequest'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportCollection() {
  return window['go']['main']['App']['ImportCollection']();
}

export function InvokeRequest(arg1) {
  return window['go']['main']['App']['InvokeRequest'](arg1);
}

export function MoveRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveRequest'](arg1, arg2, arg3, arg4);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameEnv(arg1, arg2) {
  return window['go']['main']['App']['RenameEnv'](arg1, arg2);
}

export function RenameRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameRequest'](arg1, arg2, arg3);
}

export function SelectEnv(arg1) {
  return window['go']['main']['App']['SelectEnv'](arg1);
}

export function SetSettings(arg1, arg2) {
  return window['go']['main']['App']['SetSettings'](arg1, arg2);
}

export function UpsertRequest(arg1) {
  return window['go']['main']['App']['UpsertRequest'](arg1);
}
