// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCollection(arg1:string,arg2:string):Promise<main.JSResp>;

export function AddCollectionWithParent(arg1:string,arg2:string,arg3:string):Promise<main.JSResp>;

export function AddEnv(arg1:string):Promise<main.JSResp>;

export function AddVar(arg1:string,arg2:string,arg3:string):Promise<main.JSResp>;

export function ChoseFile():Promise<main.JSResp>;

export function ClearAllCookies():Promise<main.JSResp>;

export function DeleteCollection(arg1:string):Promise<main.JSResp>;

export function DeleteCookies(arg1:string):Promise<main.JSResp>;

export function DeleteEnv(arg1:string):Promise<main.JSResp>;

export function DeleteRequest(arg1:string,arg2:string):Promise<main.JSResp>;

export function DeleteVar(arg1:string,arg2:string):Promise<main.JSResp>;

export function DuplicateEnv(arg1:string):Promise<main.JSResp>;

export function DuplicateRequest(arg1:string,arg2:string):Promise<main.JSResp>;

export function ExportCollection(arg1:string):Promise<main.JSResp>;

export function GetAllCookies():Promise<main.JSResp>;

export function GetCollections():Promise<main.JSResp>;

export function GetEnvs():Promise<main.JSResp>;

export function GetRequest(arg1:string,arg2:string):Promise<main.JSResp>;

export function GetSettings():Promise<main.JSResp>;

export function ImportCollection():Promise<main.JSResp>;

export function InvokeRequest(arg1:main.Request):Promise<main.JSResp>;

export function MoveRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.JSResp>;

export function RenameCollection(arg1:string,arg2:string):Promise<main.JSResp>;

export function RenameEnv(arg1:string,arg2:string):Promise<main.JSResp>;

export function RenameRequest(arg1:string,arg2:string,arg3:string):Promise<main.JSResp>;

export function SelectEnv(arg1:string):Promise<main.JSResp>;

export function SetSettings(arg1:string,arg2:string):Promise<main.JSResp>;

export function UpsertRequest(arg1:main.Request):Promise<main.JSResp>;
